language: java
script: mvn  clean  compile -f spring-boot-helloWorld/pom.xml

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: "AKIAJI5ETPA6DEKVPJ5Q"
    secret_access_key: "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"
    application: "HelloWorld"
    deployment_group: "DemoFleet"
    region:ap-northeast-2c
    key: spring-boot-helloWorld/target/spring-boot-helloworld-0.0.2-SNAPSHOT.jar
    bundle_type: jar    
    on:
      all_branches: true
